language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libboost1.55-all-dev
      #- libboost-date-time1.55-dev
      #- libboost-filesystem1.55-dev
      #- libboost-regex1.55-dev
      #- libboost-system1.55-dev
      #- libboost-test1.55-dev
#      - libboost-dev
      - gcc-4.8
      - g++-4.8
      - liblapack-dev


install:
    - cd ..
    - git clone https://github.com/OPM/opm-common.git
    - cd opm-common
    - mkdir build
    - cd build
    - cmake ../
    - make
    - cd ../../

    - git clone https://github.com/Ensembles/ert.git
    - cd ert
    - mkdir build
    - cd build
    - cmake ../devel/
    - make
    - cd ../../

    - cd opm-parser

before_script:
    - mkdir build
    - cd build
    - cmake ../

script: make && ctest --output-on-failure